### ISSUE TITLE
First steps with PyTorch

### ISSUE THREAD

**Issue by philippabele** [philippabele/deep-groove-with-pytorch#13]
- Start locally

https://pytorch.org/get-started/locally/

I would prefer a installation on Windows, with cuda and pip.

- Learn the basics

https://pytorch.org/tutorials/beginner/basics/intro.html

Great tutorial with all steps of a complete Machine Learning workflow

- Create a PR and add the source to our repo in an own sub folder

**Comment by RicoKursidem** [comment]
Hi,

I have a question about GitHub branches.

What is the beat practice for dealing with already closed branches. Am I supposed to delete them in my project, or can I just leave them where they are? Also, should I always take the main branch as the origin of the branch, or should I always use the last opened branch?

**Comment by philippabele** [comment]
You can delete your merged branches, but don't have to.

It is good practice so start your feature branche based on the main branche.

If the main changes and you rebase your feature branche, the changes will also be available in your feature branche.
