### ISSUE TITLE
perform an EDA on the dataset

### ISSUE THREAD

**Issue by RicoKursidem** [philippabele/deep-groove-with-pytorch#22]

**Comment by RicoKursidem** [comment]
Hi @philippabele,
 should I do the EDA in a python script or in a Jupyter file?

**Comment by philippabele** [comment]
Try to accomplish the EDA with pure python scripts.

You could reuse the produced plots within your LaTeX document.

Write your results of the EDA in a own section or chapter in your LaTeX document.
