### ISSUE TITLE
try to build your first ML model on the dataset

### ISSUE THREAD

**Issue by RicoKursidem** [philippabele/deep-groove-with-pytorch#24]

**Comment by RicoKursidem** [comment]
Hi @philippabele,

I don't think I understand what to do here. I have a dataset, and I'm supposed to feed the data to a machine learning model.
As far as I understand the subject, I can give the model some data, and it categorizes me the data points. 
In the example of the Tutorial, it was categorizing pictures of clothing.

Can you explain to me what should be the input and output of the ML model?

**Comment by philippabele** [comment]
We are now at the point where the creative part starts. I would like to survey two scenarios: 

1. Use force and speed as inputs and determine the lifetime.
2. Use lifetime and speed as inputs and determine the speed.
 
The way of modelling the challenge is free at this point, but I would recommend one which is familiar to your previous work or something you found in the tutorials. For example, are you familiar with categorization? To tune the task in this direction, just decide that you will categorize the results into certain lifetime windows.

May this help you on your journey?

**Comment by RicoKursidem** [comment]
Yes, I think that's good. Thank you.
