### ISSUE TITLE
Try out AutoML for classification

### ISSUE THREAD

**Issue by philippabele** [philippabele/deep-groove-with-pytorch#33]
After developing a model and performing a parameter study on your own, it's time for using some frameworks to support your machine learning journey.

Take a look at Auto-PyTorch

And try a basic AutoML Search for finding a better network architecture and well selected hyperparameters.

There is an example for tabular data with classification in the projects repository.

https://github.com/automl/Auto-PyTorch/blob/56a2ac1d69c7c61a847c678879a67f5d3672b3e8/examples/20_basics/example_tabular_classification.py

Focus on getting the AutoML process running. I will add an issue for documentation.

**Comment by RicoKursidem** [comment]
Hi @philippabele,
The autoPyTorch Package does not support Windows. I only work on Windows and don't have a Linux Computer. Should I try to run it on a Linux VM or set up a Computer? 

Source: https://github.com/automl/Auto-PyTorch/issues/385#issuecomment-1128569008

**Comment by philippabele** [comment]
@RicoKursidem  Do you know Docker?

You can run a plain Ubuntu Docker image with

Docker run Ubuntu bash

And install all needed tools inside the container. If you like, you could also connect vs code to work with it.

If you like. I can give you a live demo via web meeting. Just let me know.

If you are familiar with other solutions like VM feel free to select your favorite way.

**Comment by RicoKursidem** [comment]
@philippabele 

I'm familiar with docker, but I only used it to host Applications on my server.
I would like to try it via docker and connect it with VS code. Is it possible to make a meeting tomorrow or Friday?

**Comment by philippabele** [comment]
@RicoKursidem 

Please check your mail inbox 📥

**Comment by RicoKursidem** [comment]
Hi @philippabele,

 To run the docker container and the autoML application is not as straight forward as I thought. I can load the python environment and install the packages given in the autoML Installation guide. But there are Dependencies I cannot find and other errors. 
 I guess the Dependencies are there on a normal Ubuntu installation, but not on the docker container, but I did not test this on a full Linux system.

I tried to run the script from the tutorial, so it's not my code braking the program, but it did not work. 

Did you set up a python Environment before? Do you have tips for me? 
Does the Ubuntu Image contain a full Ubuntu Image or a lighter version?

**Comment by philippabele** [comment]
@RicoKursidem Did you notice the Dockerfile on the Auto-Pytorch Repository?

https://github.com/automl/Auto-PyTorch/blob/master/Dockerfile

I looks like they faced similar issues.
