### ISSUE TITLE
Write a section about AutoML for classification

### ISSUE THREAD

**Issue by philippabele** [philippabele/deep-groove-with-pytorch#34]
After closing #33 some documentation should be written down in the LaTeX documentation.

- Introduce the concept of AutoML with a paragraph
- insert plots about your application of the framework on the current dataset and describe them
- discuss the findings and the quality of the results in consideration to your intention to the classification task

**Comment by RicoKursidem** [comment]
Hi @philippabele,

I tried to figure out what the output from the PR #37 means. I think I don't understand it fully. How far I can tell is autoML a Framework to lower the barrier for new programmers by automating the parameter study and the model selection. 

The Output shows what's the best selected Model and the Preprocesses. But I don't know the models that are printed in the solution. I couldn't find a documentation of this output either or anything about, e.g., ETLearner.

The Output: https://github.com/RicoKursidem/dhbw-deep-groove-with-pytorch/blob/AutoML-Docs/docs/res/autoML.png

Could you explain in short form what I can see in the output?
Is the ETLearner a learning type for a Neural Network? (Same for SVMLearner, KNNLearner and CBLearner)

Also: I thought that weights were the values of each node to multiply with the Input. How can the whole Model get only one weight.

**Comment by philippabele** [comment]
ETLearner? That is really a good question. I don't know.

May you give the people from https://www.automl.org/ a call, write an e-mail or open a pull request at their github repository?

Feel free to start your journey to the solution :)

**Comment by RicoKursidem** [comment]
Hi @philippabele,

Ok, I will write them an e-mail about the outputs I received. If I receive an answer, I will add an explanation in the Documentation. 

I have also a question how the Project will continue. The End Date is in Two weeks and I have 5 Exams to take. 
What is planned for the next two weeks? Is there something I should rework on the documentation?

How do we handle the end of the Project? Is there an End Meeting? The DHBW wants us to make a 1-minute video presenting the Project, do you want this Video too?
